apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-deployment
  namespace: otp-namespace
  labels:
    app: otp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp
  template:
    metadata:
      labels:
        app: otp
    spec:
      containers:
        - name: otp
          image: opentripplanner/otp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: otp-config
              mountPath: /var/opentripplanner
      volumes:
        - name: otp-config
          configMap:
            name: otp-config
