apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
  namespace: otp-namespace
spec:
  selector:
    app: reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
