apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-deployment
  namespace: otp-namespace
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: nginx-config
              mountPath:  files\OpenTripPlanner\nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
