apiVersion: v1
kind: Service
metadata:
  name: web-client-service
  namespace: otp-namespace
spec:
  selector:
    app: web-client
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
